config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :user do
    root :to => 'resources#index'
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :resources do
    resources :favorites, only: :create
  end
  resources :favorites, only: [:destroy, :index]
  resources :categories, only: [:new, :create]

  get "/my_resources", to: "resources#user_resources", as: "user_resources"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :resources, only: [ :show, :create ]
    end
  end

  get "/download", to: "pages#download", as: "download"
  get "/about", to: "pages#about", as: "about"

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_tags, dependent: :destroy
  has_many :resources, through: :category_tags
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/category_tag.rb
class CategoryTag < ApplicationRecord
  belongs_to :category
  belongs_to :resource
  validates :category, uniqueness: { scope: :resource }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :resource
  belongs_to :user
  validates :user, uniqueness: { scope: :resource }
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :category_tags, dependent: :destroy
  has_many :categories, through: :category_tags
  has_one_attached :photo
  accepts_nested_attributes_for :categories, reject_if: proc { |attributes| attributes['name'].blank? }
  validates :url, url: true, presence: true, uniqueness: true
  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord

  acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :resources, dependent: :nullify
  has_many :favorites, dependent: :destroy
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/api/v1/resources_controller.rb
class Api::V1::ResourcesController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User, only: [ :create ]
  before_action :set_resource, only: [ :show ]

  def show
  end

  def create
    @resource = Resource.new(resource_params)
    photo_url = photo_params[:imgUrl]
    @resource.user = current_user
    authorize @resource
    if @resource.save
      if photo_url != ""
        ImageScrappingJob.perform_later(@resource, photo_url)
      end
      render :show, status: :created
    else
      render_error
    end
  end


private

  def set_resource
    @resource = Resource.find(params[:id])
    authorize @resource
  end

  def resource_params
    params.require(:resource).permit(:title, :description, :url)
  end

  def photo_params
    params.require(:photo).permit(:imgUrl)
  end

  def render_error
    render json: { errors: @resource.errors.full_messages },
      status: :unprocessable_entity
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) ||resources_path
  end

  def after_sign_out_path_for(resource)
    stored_location_for(resource) ||resources_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @resource = Resource.new
    @category = Category.new(params_category)
    if @category.save
      render new_resource_path
    else
      render "resources/new"
    end
  end

  private

  def params_category
    params.require(:category).permit(:name)
  end
end

app/controllers/category_tags_controller.rb
class CategoryTagsController < ApplicationController

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @resource = Resource.find(params[:resource_id])
    @favorite = Favorite.create!(user: current_user, resource: @resource)

    respond_to do |format|
      format.html { redirect_to resources_path }
      format.js
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @resource = @favorite.resource
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to resources_path }
      format.js
    end
  end

  def index
    @favorites = Favorite.includes(resource: [{photo_attachment: :blob}, :categories, :user]).where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def download
    @api_key = current_user.authentication_token
  end

  def about
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @resources = Resource.includes(:categories, :user, photo_attachment: :blob)
    p = params["/resources"]
    if !params["/resources"].nil? && p[:category].length != 1 && p[:category]
      resources = Resource.joins(:category_tags).includes(:categories, :user, photo_attachment: :blob).where(category_tags: { category: p[:category] })
      @resources = resources.uniq
    end
  end

  def show
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(resource_params)
    @resource.user = current_user
    if @resource.photo.present? && @resource.save
      redirect_to resources_path
    elsif @resource.valid?
      @resource.save
      NokogiriImageScrappingJob.perform_later(@resource.id)
      redirect_to resources_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @resource.update(resource_params)
      redirect_to resources_path
    else
      render :edit
    end
  end

  def destroy
    if @resource.user == current_user
      @resource.photo.purge if @resource.photo.attached?
      @resource.destroy
    end
    redirect_to resources_path
  end

  def user_resources
    @resources = current_user.resources.includes(:categories, :user, photo_attachment: :blob)
  end

  private

  def set_params
    @resource = Resource.find(params[:id])
  end

  def resource_params
    params.require(:resource).permit(:title, :description, :url, :photo, category_ids: [], categories_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 offset-sm-4 col-md-6 offset-md-3 form-crud mb-5">
    <h2>Catégories</h2>

      <h3>Catégories déjà existantes: </h3>
      <ul>
        <% Category.order(:name).each do |category| %>
          <li><%= category.name %></li>
        <% end %>
      </ul>
      <h4>Besoin d'en ajouter une nouvelle?</h4>
      <%= simple_form_for @category do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, 'Ajouter', class: "btn btn-primary"  %>
      <% end %>

      <%= link_to "Revenir à la page précedente", :back %>

  </div>
</div>

app/views/favorites/create.js.erb
var resourceCard = document.getElementById("resource-<%= @resource.id %>");
resourceCard.innerHTML = "<%= j render 'resources/card-index', resource: @resource %>";

app/views/favorites/destroy.js.erb
var resourceCard = document.getElementById("resource-<%= @resource.id %>");
resourceCard.innerHTML = "<%= j render 'resources/card-index', resource: @resource %>";

app/views/favorites/index.html.erb
<div class="row mt-5">
  <% @favorites.each do |favorite| %>
    <div class="col-12 col-lg-6 col-xl-4 p-4" id="resource-<%= favorite.resource.id %>">
      <%= render 'resources/card-index', resource: favorite.resource %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareYourTools</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <% unless current_page?(root_path) %>
      <%= render 'shared/navbar' %>
      <div class="container p-0">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

    <% unless current_page?(root_path) %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="wrapper-about mx-auto">
  <div class="section section-about mt-5">
    <h1 class="title">A <br> propos</h1>
    <p>Codé par 2 alumnis du Wagon Bordeaux, ShareYourTools est un moyen simple et rapide de sauvegarder vos sites préférés,
      vou pouvez les retrouver à tout moment et les partager.
      Nous faisons ce projet sur notre temps libre, et de nombreuses nouvelles fonctionnalitées devraient bientôt arriver.
      Pour nous partager vos idées ou remarques
      <%= mail_to "ecrepontvalentine@hotmail.fr", subject: "Remarques concernant ShareYourTools", target: "_blank" do %>
        c'est par ici <i class="fas fa-envelope"></i> !
      <% end %>
    </p>
    <%= image_tag "undraw_online_connection_6778.svg", alt: "" %>

  </div>

  <div class="section section-team my-5">
    <h1 class="title">La <br> team</h1>
    <div class="team-cards d-flex">

      <div class="team-card">
        <%= image_tag "vecrepont_photo.jpg", alt: "photo valentine ecrepont" %>
        <h3>Valentine Ecrepont</h3>
        <div class="social-medias">
          <%= link_to "https://www.linkedin.com/in/valentine-ecrepont-539519197/", target: "_blank" do %>
            <i class="fab fa-linkedin"></i>
          <% end %>
          <%= link_to "https://github.com/Eval160", target: "_blank"  do %>
            <i class="fab fa-github"></i>
          <% end %>
          <%= link_to "https://twitter.com/Eval160", target: "_blank"  do %>
            <i class="fab fa-twitter"></i>
          <% end %>
          <%= mail_to "ecrepontvalentine@gmail.com", target: "_blank" do %>
            <i class="fas fa-at"></i>
          <% end %>
        </div>
        <p>Développeuse web Ruby on Rails et Javascript, passionnée d'UX et particulièrement sensible à l'accessibilité et à l'éco-conception web.</p>
        <%= link_to "Portfolio", "#", target: "_blank", class: "btn btn-outline-primary"%>
      </div>

      <div class="team-card">
        <%= image_tag "jprevost_photo.jpg", alt: "photo valentine ecrepont" %>
        <h3>Jules Prévost</h3>
        <div class="social-medias">
          <%= link_to "https://www.linkedin.com/in/prevostjules/", target: "_blank" do %>
            <i class="fab fa-linkedin"></i>
          <% end %>
          <%= link_to "https://github.com/prevostjules", target: "_blank"  do %>
            <i class="fab fa-github"></i>
          <% end %>
          <%= link_to "https://twitter.com/prevost_jules", target: "_blank"  do %>
            <i class="fab fa-twitter"></i>
          <% end %>
          <%= mail_to "jules@prevostdev.com", target: "_blank" do %>
            <i class="fas fa-at"></i>
          <% end %>
        </div>
        <p>Développeur web (Ruby On Rails) freelance, Teacher Assistant au Wagon Bordeaux et journaliste pigiste pour GEO, Le Monde, Le Figaro Magazine, La Vie et quelques autres.</p>
        <%= link_to "Portfolio", "https://www.prevostdev.com", target: "_blank", class: "btn btn-outline-primary"%>
      </div>


    </div>
  </div>
</div>

app/views/pages/download.html.erb
<div class="card card-tuto">
  <h2>Comment installer notre extension Chrome ?</h2>

  <ol>
    <li>Cliquer sur ce <a href="https://github.com/prevostjules/dev_tools_extension_chrome/archive/master.zip" class="btn btn-primary">bouton</a> bouton pour télécharger l’extension</li>
    <li>Cliquer deux fois sur le fichier dev_tools_extension_chrome-master.zip pour le dézipper</li>
    <li>Ouvrir le navigateur Chrome, Chromium ou Brave</li>
    <li>Cliquer sur en haut à droite de votre fenêtre sur <i class="fas fa-bars"></i> puis sélectionner "Extensions"</li>
    <li>Notre extension n’a pas encore été validé par le Chrome Store. Pour pouvoir profiter de ses magnifiques fonctionnalités, vous devez activer le "Mode développeur" en cliquant sur <i class="fas fa-toggle-on"></i> en haut à droite de votre fenêtre</li>
    <li>Appuyer sur "Charger l’extension non empaquetée" puis sélectionner le dossier "dev_tools_extension_chrome-master"</li>
    <li>Appuyez sur la pièce de puzzle <i class="fas fa-puzzle-piece"></i> à droite de vos extensions déjà installées</li>
    <li>Appuyer sur la punaise: <i class="fas fa-thumbtack"></i> pour afficher Dev Tools en permanence</i></li>
  </ol>

  <p>Voilà votre extension est désormais fonctionnelle ! Vous n’avez plus qu’à rentrer votre mail et votre clé api pour en profiter !</p>
  <div class="text-center">
    <p>Votre clé api : <strong><%= @api_key %></strong></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage_wrapper d-flex align-items-center">
  <div class="container">
    <h1>Bienvenu sur <strong>ShareYourTools</strong></h1>
    <h2>Site de partage de ressources pour les développeurs </h2>
    <p>Les favoris de votre navigateur s'entassent et vous avez du mal à vous y retrouvez?</p>
    <p>Vous voulez partager avec la communauté des sites fascinants?</p>
    <p>Quelque soit la raison, cette application est faite pour vous</p>
    <%= link_to "Voir les sites",resources_path, class: "btn btn-light" %>
    <% unless user_signed_in? %>
      <%= link_to "Se connecter",new_user_session_path, class: "btn btn-outline-light" %>
    <% end %>
  </div>
</div>

app/views/resources/_card-index.html.erb
<div class="card-resource" style="--background:#213E69; --text:white;">
  <div class="multi-button">
    <% if signed_in? && current_user.favorites.find_by(resource: resource) %>
      <%= link_to favorite_path(current_user.favorites.find_by(resource: resource)), method: :delete, remote: true  do %>
        <i class="fas fa-heart"></i>
       <% end %>
    <% elsif  signed_in?%>
      <%= link_to resource_favorites_path(resource), method: :post, remote: true  do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
         <i class="far fa-heart"></i>
      <% end %>
    <% end %>
    <%= link_to edit_resource_path(resource)  do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to resource_path(resource), class: "#{'d-none' if resource.user != current_user}" , method: :delete do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
  <% if resource.photo.attached?  %>
    <div class="content" style="background-image: url('<%= cl_image_path resource.photo.key, height: 250, width: 400, crop: :fill %>')">
  <% else %>
    <div class="content" style="background-image: url('https://images.unsplash.com/photo-1489844097929-c8d5b91c456e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1652&q=80')">
  <% end %>
      <div class="header d-flex justify-content-between">
        <%= link_to resource.url , class: "d-flex" , target: "_blank" do %>
          <h3><%= resource.title %></h3>
          <i class="fas fa-external-link-alt ml-2"></i>
        <% end %>
      </div>
      <div class="description">
        <p><%= resource.description %></p>
      </div>

      <div class="card-resource_tag">
        <% resource.categories.each do |category| %>
          <span class="badge badge-primary"><%= category.name %></span>
        <% end %>
      </div>
  </div>
</div>

app/views/resources/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 offset-sm-3 form-crud mb-5">
    <h2> <%= @resource.new_record? ? "Ajouter un site" : @resource.title %></h2>
    <%= simple_form_for @resource do |f| %>
      <fieldset class="form-group ">
        <legend class="col-form-label pt-0">Choississez une ou plusieurs catégories</legend>
        <small class="form-text text-muted mb-3">Plusieurs choix possibles</small>
        <input type="hidden" name="resource[category_ids][]" value="">
        <div class="category-choices">
          <% Category.order(:name).each do |category| %>
            <input class="d-none" type="checkbox" value="<%= category.id %>" name="resource[category_ids][]" id="resource_category_ids_<%= category.id %>" <%= "checked='true'" if @resource.categories.include?(category) %> >
            <label class="category-choice <%= 'active' if @resource.categories.include?(category) %>" for="resource_category_ids_<%= category.id %>"><%= category.name %></label>
          <% end %>
        </div>

        <div>
          <label for="resource_categories_attributes_0_name">Autre ?</label>
          <%= f.fields_for :categories, Category.new do |category_attributes|%>
              <%= category_attributes.text_field :name, class: "form-control" %>
          <% end %>
        </div>
      </fieldset>

      <div class="d-flex justify-content-between resources_inline-input">
        <%= f.input :title, placeholder: "Site du Zero" %>
        <%= f.input :url, placeholder: "https://supersite.com" %>
      </div>

      <div class="btn btn-primary d-inline-flex align-items-center", id="upload-btn">
        <i class="fas fa-upload"></i>
        <%= f.input :photo, as: :file, label: "Charger une photo" %>
      </div>

      <%= f.input :description %>
      <%= f.button :submit, 'Ajouter', class: "btn btn-primary"  %>
    <% end %>
      <%= link_to "Revenir à la page précedente", :back %>
  </div>
</div>

app/views/resources/edit.html.erb
<%= render "form", resource: @resource %>

app/views/resources/index.html.erb
<div class="category-filter_section">
  <%= submit_tag "Filtrer par catégorie", class: "toogleBtn btn btn-primary mt-4 mb-2" %>
  <%= simple_form_for resources_path, method: "get" do |f|%>
    <div class="category-filter d-none ">
      <%= f.input :category, as: :check_boxes, collection: Category.all, input_html: { class: 'd-none' }   %>
      <%= f.submit "Go !", class: "btn btn-primary filter-btn"%>
    </div>
  <% end %>

</div>

<div class="row">
  <% @resources.shuffle.each do |resource| %>
    <div class="col-12 col-lg-6 col-xl-4 p-4" id="resource-<%= resource.id %>">
      <%= render 'card-index', resource: resource %>
    </div>
  <% end %>
</div>

app/views/resources/new.html.erb
<%= render "form", resource: @resource %>

app/views/resources/user_resources.html.erb
<div class="row mt-5">
  <% @resources.each do |resource| %>
    <div class="col-12 col-lg-6 col-xl-4 p-4" id="resource-<%= resource.id %>">
      <%= render 'card-index', resource: resource %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-medias">
    <%= link_to "https://www.linkedin.com/in/valentine-ecrepont-539519197/", target: "_blank" do %>
      <i class="fab fa-linkedin"></i>
    <% end %>
    <%= link_to "https://github.com/Eval160", target: "_blank"  do %>
      <i class="fab fa-github"></i>
    <% end %>
    <%= link_to "https://twitter.com/Eval160", target: "_blank"  do %>
      <i class="fab fa-twitter"></i>
    <% end %>
    <%= mail_to "ecrepontvalentine@hotmail.fr", target: "_blank", subject: "Remarque à propos de site 'My dev tools links'" do %>
      <i class="fas fa-at"></i>
    <% end %>
  </div>
  <p>Fait avec amour depuis Bordeaux <i class="fas fa-hand-holding-heart"></i></p>
  <p>© Valentine Ecrepont - 2020 </p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbar-logo">
    <%= link_to root_path , class: "navbar-brand" do %>
      <%= image_tag "logo-blue-bg.png", alt: "logo" %>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Les sites", resources_path, class: "nav-link text-uppercase" %>
      </li>
      <li class="nav-item">
        <%= link_to "A propos", about_path, class: "nav-link text-uppercase" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Ajouter un site", new_resource_path, class: "nav-link text-uppercase"  %>
          <%#= link_to "Cheatsheets", "#", class: "nav-link text-uppercase" %>
        </li>
        <li class="nav-item dropdown">
          <i class="far fa-user dropdown-toggle" id="navbarDropdown", data-toggle="dropdown", aria-haspopup=true, aria-expanded=false ></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mes favoris", favorites_path, class: "dropdown-item" %>
            <%= link_to "Mes sites partagés", user_resources_path, class: "dropdown-item"  %>
            <%= link_to "Télécharger l'extension", download_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link text-uppercase" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>